In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [ ]:
!pip install transformers

In [ ]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.4 MB/s eta 0:00:00


In [ ]:
import torch
import torch.nn as nn
from datasets import load_dataset

# 데이터 셋
- 기계 번역 : 영 -> 독

In [ ]:
dataset = load_dataset("wmt16", "de-en")
dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/4548885 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2169 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2999 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 4548885
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 2169
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2999
    })
})

In [ ]:
for meta in dataset['train']:
  print (meta)
  break

{'translation': {'de': 'Wiederaufnahme der Sitzungsperiode', 'en': 'Resumption of the session'}}


### 토크나이저 로드 : nltk

In [ ]:
!pip install nltk

In [ ]:
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
word_tokenize('Resumption of the session')

['Resumption', 'of', 'the', 'session']

- valid set : test set 진행

- token preprocessing

In [ ]:
# token 중복 방지
word_list = set()
for data in dataset['validation']:
  for word in word_tokenize(data['translation']['en']):
    word_list.add(word)
  for word in word_tokenize(data['translation']['de']):
    word_list.add(word)
for data in dataset['test']:
  for word in word_tokenize(data['translation']['en']):
    word_list.add(word)
  for word in word_tokenize(data['translation']['de']):
    word_list.add(word)

In [ ]:
word_list

{'sichergestellt',
 'Absatz',
 'Partie',
 'anfing',
 'Documents',
 'advisor',
 'HTA',
 '350th',
 'Aktualisierung',
 'Ermittlungen',
 'krank',
 'teachers',
 'gelangt',
 'Standards',
 'participating',
 'Concerns',
 '1967',
 'volunteer',
 'still',
 'GP',
 'lehnt',
 'amerikanisches',
 'Viererkette',
 'guard',
 'back-ordered',
 'intertwined',
 'Atlanta',
 'Zwist',
 'carry',
 'Bullets',
 'overhang',
 'votes',
 'extremely',
 'Vorgänge',
 'Private',
 'Stationierungen',
 'ganzes',
 'Burgvereinen',
 'Kern',
 'unterhalb',
 'Hämoglobin',
 'anderen',
 'EU-Warnsystem',
 'passen',
 'raptures',
 'redesigned',
 'Kanalisation',
 'Freitagabend',
 'Erhöhungen',
 'Autofahrer',
 'blockiert',
 'zweispurig',
 'troubles',
 'hochautomatisiertes',
 'mirrored',
 'Mund',
 'Dow',
 'Regenschauern',
 'Gepflegte',
 'erscheint',
 'Wachstafeln',
 'Donnerstag',
 'vorgesehene',
 'Ihr',
 'Lesser',
 'Wawrinka',
 'nichtlegislativen',
 'gladiator',
 '€10',
 'direkt',
 'definitely',
 'Unruhe',
 'Figur',
 'Hollywoodproduktionen

In [ ]:
len(word_list)

30164

In [ ]:
special_tokens = ['<SOS>', '<EOS>', '<PAD>', '<UNK>']

token2id = {}
id2token = set()

for token in word_list:
    id2token.add(token)
id2token = sorted(list(id2token))
if special_tokens:
    for token in special_tokens:
        id2token.insert(0, token)

for i, token in enumerate(id2token):
    token2id[token] = i

In [ ]:
token2id

{'<UNK>': 0,
 '<PAD>': 1,
 '<EOS>': 2,
 '<SOS>': 3,
 '!': 4,
 '#': 5,
 '$': 6,
 '%': 7,
 '&': 8,
 "'": 9,
 "''": 10,
 "'37": 11,
 "'American": 12,
 "'Cherie": 13,
 "'Cycling": 14,
 "'Damir": 15,
 "'Date": 16,
 "'Geschossen": 17,
 "'Help": 18,
 "'Ich": 19,
 "'If": 20,
 "'In": 21,
 "'It": 22,
 "'Mummy": 23,
 "'Oh": 24,
 "'Our": 25,
 "'Plotting": 26,
 "'Run": 27,
 "'Shot": 28,
 "'Sonogenetics": 29,
 "'Stop": 30,
 "'Sunrise": 31,
 "'They": 32,
 "'This": 33,
 "'Three": 34,
 "'Tod": 35,
 "'We": 36,
 "'You": 37,
 "'cheap": 38,
 "'chirurgischen": 39,
 "'come": 40,
 "'d": 41,
 "'death": 42,
 "'die": 43,
 "'dumbing": 44,
 "'from": 45,
 "'ghost": 46,
 "'golden": 47,
 "'ll": 48,
 "'m": 49,
 "'my": 50,
 "'n": 51,
 "'pig": 52,
 "'plotting": 53,
 "'quality": 54,
 "'re": 55,
 "'s": 56,
 "'shut": 57,
 "'statehood": 58,
 "'ve": 59,
 '(': 60,
 ')': 61,
 '*': 62,
 '+': 63,
 '+2': 64,
 '+44': 65,
 ',': 66,
 '-': 67,
 '--': 68,
 '-Bericht': 69,
 '-Film': 70,
 '-Kindergartens': 71,
 '-Protesten': 72,
 '-Zeit

In [ ]:
token2id['<UNK>'], token2id['<SOS>']

(0, 3)

In [ ]:
token2id['Apple']

1656

In [ ]:
id2token[0], id2token[1], id2token[2], id2token[3]

('<UNK>', '<PAD>', '<EOS>', '<SOS>')

# dataset

- dataset

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class NMTDataset(Dataset):
  def __init__(self, data, token2id):
    self.data = data
    self.src = []
    self.tgt = []
    self.src_mask = []
    self.tgt_mask = []

    max_len = 64

    for meta in data:
      temp1 = []
      mask=[]
      length=0

      # tokenization : pred
      for s in word_tokenize(meta['translation']['de'])[:62]: # sos, eos 추가 : 62 + 2 = 64(max length)
        length += 1
        try:
          temp1.append(token2id[s])
        except:
          temp1.append(token2id['<UNK>'])
      temp1.insert(0, token2id['<SOS>'])
      temp1.append(token2id['<EOS>'])
      length += 2
      for _ in range(length):
        mask.append(1)
      for _ in range(max_len - length):
        temp1.append(token2id['<PAD>'])
        mask.append(0)

      # mask(1 연산, 0 연산 x)
      self.src.append(temp1)
      self.src_mask.append(mask)
      temp2 = []
      length = 0

      # tokenizer : target
      for s in word_tokenize(meta['translation']['en'])[:62]:
        length += 1
        try:
          temp2.append(token2id[s])
        except:
          temp2.append(token2id['<UNK>'])
      temp2.insert(0, token2id['<SOS>'])
      temp2.append(token2id['<EOS>'])
      length += 2
      mask = []
      for _ in range(length):
        mask.append(1)
      for _ in range(max_len - length):
        temp2.append(token2id['<PAD>'])
        mask.append(0)
      self.tgt.append(temp2)
      self.tgt_mask.append(mask)


  def __len__(self):
    return len(self.data)


  def __getitem__(self, idx):
    return torch.tensor(self.src[idx]), torch.tensor(self.src_mask[idx]), torch.tensor(self.tgt[idx]), torch.tensor(self.tgt_mask[idx])

In [ ]:
train_data = NMTDataset(dataset['validation'], token2id)
valid_data = NMTDataset(dataset['test'], token2id)

- dataloader

In [ ]:
train_loader = DataLoader(train_data, shuffle=True, batch_size=64)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=64)

In [ ]:
train_data.__getitem__(0)[0]

tensor([    3,  3664,  9861,  6570, 28100,  6815, 27768, 26300, 21487, 12453,
           76,     2,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1])

In [ ]:
train_data.__getitem__(0)[1]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
train_data.__getitem__(0)[2]

tensor([    3,  6567, 14723,  6813, 24608, 23099, 22942, 21487, 12455,     2,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1])

In [ ]:
train_data.__getitem__(0)[3]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Modeling

In [ ]:
from torch import nn


class ParameterSharedTransformerEncoder(nn.TransformerEncoder):
    def __init__(
        self,
        d_model=512,
        nhead=8,
        dim_feedforward=2048,
        dropout=0.1,
        activation="relu",
        num_unique_layers=3, # M
        num_total_layers=6, # N : 총 레이어 갯수
        mode="cycle_rev",
        norm=False,
    ):
        assert mode in {"sequence", "cycle", "cycle_rev"}
        quotient, remainder = divmod(num_total_layers, num_unique_layers)
        assert remainder == 0
        if mode == "cycle_rev":
            assert quotient == 2
        encoder_layer = nn.TransformerEncoderLayer(
            d_model, nhead, dim_feedforward, dropout, activation, batch_first=True
        )
        super().__init__(encoder_layer, num_layers=num_unique_layers, norm=norm)
        self.N = num_total_layers
        self.M = num_unique_layers
        self.mode = mode
        self.norm = nn.LayerNorm(d_model) if norm else None

    def forward(self, x, mask=None, src_key_padding_mask=None, verbose=False):
        for i in range(self.N):
            if self.mode == "sequence":
                i = i // (self.N // self.M)
            elif self.mode == "cycle":
                i = i % self.M
            elif i > (self.N - 1) / 2:
                i = self.N - i - 1
            if verbose:
                print(f"layer {i}")
            x = self.layers[i](x, mask, src_key_padding_mask)
        if self.norm is not None:
            x = self.norm(x)
        return x



- encoder / decoder

In [ ]:
encoder = ParameterSharedTransformerEncoder()

decoder_layer = nn.TransformerDecoderLayer(d_model=512, nhead=8, batch_first=True)
decoder = nn.TransformerDecoder(decoder_layer, num_layers=6)

classification_layer = nn.Linear(512, len(token2id))

- param

In [ ]:
de_params = decoder.parameters()

- embedding

In [ ]:
embedding = nn.Embedding(len(token2id), 512, padding_idx=1)

# Train

In [52]:
epochs = 5
learning_rate=0.005

In [53]:
optimizer = torch.optim.Adam(list(embedding.parameters())+list(encoder.parameters())+list(de_params)+list(classification_layer.parameters()), lr=learning_rate)

In [54]:
loss_func = nn.CrossEntropyLoss(ignore_index=1)

- train

In [55]:
for epoch in range(1, epochs):
  for i, batch_data in enumerate(train_loader):
    optimizer.zero_grad()
    src, src_mask, tgt, tgt_mask = batch_data
    emb = embedding(src)
    tgt_emb = embedding(tgt)
    memory = encoder(emb, src_mask.bool())
    out = decoder(tgt_emb, memory, tgt_mask.bool(), src_mask.bool())
    out = classification_layer(out.view(-1,512))
    loss = loss_func(out, tgt.view(-1))
    loss.backward()
    optimizer.step()

KeyboardInterrupt: 

# evaluation

In [56]:
from nltk.translate.bleu_score import sentence_bleu

In [57]:
reference = [["this", "is", "the", "not", "sample", "banana"]]
candidate = ['this', "is", "the", "sample", "apple"]

score = sentence_bleu(reference, candidate, weights=(0.25, 0.25, 0.25, 0.25))

/usr/local/lib/python3.10/dist-packages/nltk/translate/bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)


In [58]:
score

6.042433724643145e-78

In [ ]:
for i, batch_data in enumerate(valid_loader):
  src, src_mask, tgt, tgt_mask = batch_data
  emb = embedding(src)
  enc_vector = encoder(emb, src_mask.bool())
  length = 1
  ys = torch.ones(src.size(0), 1).fill_(token2id['<SOS>']).type(torch.long)
  while length < 64: # max sequence length
      tgt_emb = embedding(ys)
      out = decoder(tgt_emb, enc_vector)
      prob = classification_layer(out[:, -1])
      next_word = torch.argmax(prob, dim=-1)
      next_word = next_word.item()
      ys = torch.cat([ys, torch.ones(1, 1).type(torch.long).fill_(next_word)], dim=1)

      len += 1
      if next_word == token2id['<EOS>']:
          break

  sentence = [id2token(w) for w in ys]
  target = [id2token(w) for w in tgt]
  score = sentence_bleu(sentence, target)