In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [3]:
!pip install transformers

In [4]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 8.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 15.1 MB/s eta 0:00:00


In [5]:
import torch
import torch.nn as nn
from datasets import load_dataset

# 데이터 셋
- 기계 번역 : 영 -> 독

In [6]:
dataset = load_dataset("wmt16", "de-en")
dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/4548885 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2169 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2999 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 4548885
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 2169
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2999
    })
})

In [7]:
for meta in dataset['train']:
  print (meta)
  break

{'translation': {'de': 'Wiederaufnahme der Sitzungsperiode', 'en': 'Resumption of the session'}}


### 토크나이저 로드 : nltk

In [9]:
!pip install nltk

In [10]:
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [15]:
word_tokenize('Resumption of the session')

['Resumption', 'of', 'the', 'session']

- valid set : test set 진행

- token preprocessing

In [16]:
# token 중복 방지
word_list = set()
for data in dataset['validation']:
  for word in word_tokenize(data['translation']['en']):
    word_list.add(word)
  for word in word_tokenize(data['translation']['de']):
    word_list.add(word)
for data in dataset['test']:
  for word in word_tokenize(data['translation']['en']):
    word_list.add(word)
  for word in word_tokenize(data['translation']['de']):
    word_list.add(word)

In [18]:
word_list

{'Jayawardene',
 'Bauvorhaben',
 'fraction',
 'Berngauer',
 'maintains',
 'vorliegt',
 'französische',
 'Memoiren',
 'Lesser',
 'unterstützte',
 'Polish',
 'hovered',
 'Bekanntgabe',
 'wiseacres',
 'Reconstruction',
 'Broncos',
 'pre-season',
 'schätzen',
 'Belastungsstörung',
 'targeting',
 'prevail',
 'ausgestattete',
 'Olivier',
 'adviser',
 'Sanders',
 'mahnt',
 'tightness',
 'wheelchair',
 'sehr',
 'setting',
 'Referenzen',
 'impacting',
 'upon',
 'simply',
 'dreamed',
 'Noch',
 'Traktorfahrer',
 'sale',
 'lebenslustig',
 'Konzert',
 'Sportpistolen',
 'Quinnipiac',
 'Xi',
 'rehabilitation',
 'rape',
 'seconds',
 'friendships',
 'abuse',
 'Schuppendächer',
 'Wunder',
 'Misstrauen',
 'Baruch',
 'bright',
 'Ausländern',
 'checks',
 'Ekaterinburg',
 'Kerle',
 'Tölzer',
 'empire',
 'einzugreifen',
 'leben',
 'Tisch',
 'Klamotten',
 'How',
 'Mayoress',
 'kommentieren',
 'audience',
 'hängt',
 'if',
 'long-time',
 'Packard',
 'Gattin',
 'vorwerfen',
 'Jause',
 'spending',
 'games',
 'Dem

In [17]:
len(word_list)

30164

In [19]:
special_tokens = ['<SOS>', '<EOS>', '<PAD>', '<UNK>']

token2id = {}
id2token = set()

for token in word_list:
    id2token.add(token)
id2token = sorted(list(id2token))
if special_tokens:
    for token in special_tokens:
        id2token.insert(0, token)

for i, token in enumerate(id2token):
    token2id[token] = i

In [24]:
token2id

{'<UNK>': 0,
 '<PAD>': 1,
 '<EOS>': 2,
 '<SOS>': 3,
 '!': 4,
 '#': 5,
 '$': 6,
 '%': 7,
 '&': 8,
 "'": 9,
 "''": 10,
 "'37": 11,
 "'American": 12,
 "'Cherie": 13,
 "'Cycling": 14,
 "'Damir": 15,
 "'Date": 16,
 "'Geschossen": 17,
 "'Help": 18,
 "'Ich": 19,
 "'If": 20,
 "'In": 21,
 "'It": 22,
 "'Mummy": 23,
 "'Oh": 24,
 "'Our": 25,
 "'Plotting": 26,
 "'Run": 27,
 "'Shot": 28,
 "'Sonogenetics": 29,
 "'Stop": 30,
 "'Sunrise": 31,
 "'They": 32,
 "'This": 33,
 "'Three": 34,
 "'Tod": 35,
 "'We": 36,
 "'You": 37,
 "'cheap": 38,
 "'chirurgischen": 39,
 "'come": 40,
 "'d": 41,
 "'death": 42,
 "'die": 43,
 "'dumbing": 44,
 "'from": 45,
 "'ghost": 46,
 "'golden": 47,
 "'ll": 48,
 "'m": 49,
 "'my": 50,
 "'n": 51,
 "'pig": 52,
 "'plotting": 53,
 "'quality": 54,
 "'re": 55,
 "'s": 56,
 "'shut": 57,
 "'statehood": 58,
 "'ve": 59,
 '(': 60,
 ')': 61,
 '*': 62,
 '+': 63,
 '+2': 64,
 '+44': 65,
 ',': 66,
 '-': 67,
 '--': 68,
 '-Bericht': 69,
 '-Film': 70,
 '-Kindergartens': 71,
 '-Protesten': 72,
 '-Zeit

In [21]:
token2id['<UNK>'], token2id['<SOS>']

(0, 3)

In [22]:
token2id['Apple']

1656

In [27]:
id2token[0], id2token[1], id2token[2], id2token[3]

('<UNK>', '<PAD>', '<EOS>', '<SOS>')

# dataset

- dataset

In [28]:
from torch.utils.data import Dataset, DataLoader

In [30]:
class NMTDataset(Dataset):
  def __init__(self, data, token2id):
    self.data = data
    self.src = []
    self.tgt = []
    self.src_mask = []
    self.tgt_mask = []

    max_len = 64

    for meta in data:
      temp1 = []
      mask=[]
      length=0

      # tokenization : pred
      for s in word_tokenize(meta['translation']['de'])[:62]: # sos, eos 추가 : 62 + 2 = 64(max length)
        length += 1
        try:
          temp1.append(token2id[s])
        except:
          temp1.append(token2id['<UNK>'])
      temp1.insert(0, token2id['<SOS>'])
      temp1.append(token2id['<EOS>'])
      length += 2
      for _ in range(length):
        mask.append(1)
      for _ in range(max_len - length):
        temp1.append(token2id['<PAD>'])
        mask.append(0)

      # mask(1 연산, 0 연산 x)
      self.src.append(temp1)
      self.src_mask.append(mask)
      temp2 = []
      length = 0

      # tokenizer : target
      for s in word_tokenize(meta['translation']['en'])[:62]:
        length += 1
        try:
          temp2.append(token2id[s])
        except:
          temp2.append(token2id['<UNK>'])
      temp2.insert(0, token2id['<SOS>'])
      temp2.append(token2id['<EOS>'])
      length += 2
      mask = []
      for _ in range(length):
        mask.append(1)
      for _ in range(max_len - length):
        temp2.append(token2id['<PAD>'])
        mask.append(0)
      self.tgt.append(temp2)
      self.tgt_mask.append(mask)


  def __len__(self):
    return len(self.data)


  def __getitem__(self, idx):
    return torch.tensor(self.src[idx]), torch.tensor(self.src_mask[idx]), torch.tensor(self.tgt[idx]), torch.tensor(self.tgt_mask[idx])

In [31]:
train_data = NMTDataset(dataset['validation'], token2id)
valid_data = NMTDataset(dataset['test'], token2id)

- dataloader

In [33]:
train_loader = DataLoader(train_data, shuffle=True, batch_size=64)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=64)

In [34]:
train_data.__getitem__(0)[0]

tensor([    3,  3664,  9861,  6570, 28100,  6815, 27768, 26300, 21487, 12453,
           76,     2,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1])

In [35]:
train_data.__getitem__(0)[1]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
train_data.__getitem__(0)[2]

tensor([    3,  6567, 14723,  6813, 24608, 23099, 22942, 21487, 12455,     2,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1])

In [38]:
train_data.__getitem__(0)[3]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])